NguyenVanTien_B8209_E_Project/E_Project/E_Project/Controllers/DetailController.cs
using E_Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ModelEntity;
using ModelEntity.Frameworks;
using E_Project.Areas.Admin.Utils;

namespace E_Project.Controllers
{
    public class DetailController : Controller
    {
        // GET: Detail
        public ActionResult Index(int id, string type)
        {
            if (id < 1)
            {
                return RedirectToAction("Index","Home");
            } else
            {
                InfoSession modelSession = new InfoSession();

                modelSession = SessionHelper.GetInfoSession();
                Session["infoSession"] = modelSession;
                DetailModel detailModel = new DetailModel();
                if (type.Equals("PLAN"))
                {
                    var planDBModel = new PlanDBModel();
                    var model = planDBModel.getPlanById(id);
                    detailModel.id = model.N_ID;
                    detailModel.name = model.S_NAME;
                    detailModel.type = type;
                    detailModel.detail = model.S_DETAIL;
                    detailModel.description = model.S_DESCRIPTION;
                    detailModel.total = 1;
                }
                else
                {
                    var productDBModel = new ProductDBModel();
                    var model = productDBModel.getProductById(id);
                    detailModel.id = model.N_ID;
                    detailModel.name = model.S_NAME;
                    detailModel.type = type;
                    detailModel.detail = model.S_DETAIL;
                    detailModel.description = model.S_DESCRIPTION;
                    detailModel.price = model.N_PRICE;
                    detailModel.total = 1;
                }
                return View(detailModel);
            }
            
        }

        public ActionResult Create(int id, string type, double price, int total)
        {
            InfoSession modelSession = new InfoSession();

            modelSession = SessionHelper.GetInfoSession();
            if (modelSession == null)
            {
                return RedirectToAction("Login", "User");
            }
            else
            {
                
                var orderDBModel = new OrderDBModel();
                TB_ORDER order = new TB_ORDER();
                order.N_AMOUNT = price * total;
                order.N_TOTAL = total;
                order.S_TYPE = type;
                order.S_CUSTOMER_NAME = modelSession.fullName;
                order.S_PHONE = modelSession.phone;
                order.S_ADDRESS = modelSession.address;
                order.N_CUSTOMER_ID = modelSession.id;
                orderDBModel.createOrder(order, id);
                return RedirectToAction("Index","Card");
            }

        }
    }
}

NguyenVanTien_B8209_E_Project/E_Project/E_Project/Controllers/ProductListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using E_Project.Models;
using ModelEntity;
using E_Project.Areas.Admin.Model;
using E_Project.Areas.Admin.Utils;
using ModelEntity.Frameworks;

namespace E_Project.Controllers
{
    public class ProductListController : Controller
    {
        // GET: ProductList
        public ActionResult Index()
        {
            InfoSession modelSession = new InfoSession();

            modelSession = SessionHelper.GetInfoSession();
            Session["infoSession"] = modelSession;
            var productModelDB = new ProductDBModel();
            var planModelDB = new PlanDBModel();
            IndexModel model = new IndexModel();
            model.Products = productModelDB.getListProduct();
            model.Plans = planModelDB.getListPlan();
            return View(model);
        }
    }
}

NguyenVanTien_B8209_E_Project/E_Project/E_Project/Controllers/UserController.cs
using E_Project.Areas.Admin.Model;
using E_Project.Areas.Admin.Utils;
using ModelEntity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ModelEntity.Frameworks;

namespace E_Project.Controllers
{
    public class UserController : Controller
    {
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel model)
        {
            if (model.account == null)
            {
                model.account = "";
            }
            if (model.password == null)
            {
                model.password = "";
            }
            var checkLogin = new CustomerDBModel().Login(model.account, model.password);
            if (checkLogin != 0 && ModelState.IsValid)
            {
                var result = new CustomerDBModel().getCustomer(model.account, model.password);
                SessionHelper.SetSession(new InfoSession() { id = result.N_ID, account = result.S_ACCOUNT, password = result.S_PASSWORD, fullName = result.S_NAME, address = result.S_ADDRESS, phone = result.S_PHONE });
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("", "Login failed, please try again !");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Register()
        {
            var customerModel = new CustomerModel();
            return View(customerModel);
        }

        [HttpPost]
        public ActionResult Register(CustomerModel model)
        {
            try
            {
                    var modelDB = new CustomerDBModel();
                    TB_CUSTOMER customer = new TB_CUSTOMER();
                    customer.S_ACCOUNT = model.account;
                    customer.S_PASSWORD = model.password;
                    customer.S_NAME = model.customerName;
                    customer.S_PHONE = model.phone;
                    customer.S_ADDRESS = model.address;
                    customer.S_DESCRIPTION = model.description;
                    modelDB.registerCustomer(customer);

                    return RedirectToAction("Login");
                
            }
            catch
            {
                return View();
            }
        }
    }
}

NguyenVanTien_B8209_E_Project/E_Project/E_Project/Views/ProductList/Index.cshtml
@{
    Layout = "~/Views/Shared/_layout.cshtml";
}
@using E_Project.Areas.Admin.Utils
@model E_Project.Models.IndexModel
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div class="container">
        <section class="py-5 bg-light">
            <div class="container">
                <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
                    <div class="col-lg-6">
                        <h1 class="h2 text-uppercase mb-0">PRODUCT</h1>
                    </div>
                    <div class="col-lg-6 text-lg-right">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb justify-content-lg-end mb-0 px-0">
                                <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">PRODUCT</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </section>
      
        <!-- TRENDING PRODUCTS-->
        <section class="py-5">
            <header>
                <p class="small text-muted small text-uppercase mb-1">Made the hard way</p>
                <h2 class="h5 text-uppercase mb-4">Products</h2>
            </header>
            <div class="row">
                <!-- PRODUCT-->
                @foreach (var item in Model.Products)
                {

                    <div class="col-xl-4 col-lg-4 col-sm-6">
                        <div class="product text-center">
                            <div class="position-relative mb-3">
                                <div class="badge text-white badge-"></div><a class="d-block" href="@Url.Action("Index","Detail", new { id = @item.N_ID, type = "PRODUCT"})"><img class="img-fluid w-100" src="~/Assets/Admin/img/@item.S_DETAIL" alt="..." style="height:350px !important"></a>
                                <div class="product-overlay">
                                    <ul class="mb-0 list-inline">
                                        @*<li class="list-inline-item m-0 p-0"><a class="btn btn-sm btn-outline-dark" href="#"><i class="far fa-heart"></i></a></li>*@
                                        @if (Session["inforSession"] == null)
                                        {
                                            <li class="list-inline-item m-0 p-0"><a class="btn btn-sm btn-dark" href="@Url.Action("Login","User")">Add to cart</a></li>
                                        }
                                        else
                                        {
                                            <li class="list-inline-item m-0 p-0"><a class="btn btn-sm btn-dark" href="@Url.Action("Index","Detail", new { id = @item.N_ID, type = "PRODUCT"})">Detail</a></li>
                                        }

                                        @*<li class="list-inline-item mr-0"><a class="btn btn-sm btn-outline-dark" href="#productView" data-toggle="modal"><i class="fas fa-expand"></i></a></li>*@
                                    </ul>
                                </div>
                            </div>
                            <h6> <a class="reset-anchor" href="detail.html">@item.S_NAME</a></h6>
                            <p class="small text-muted">$@item.N_PRICE</p>
                        </div>
                    </div>

                }

            </div>
        </section>

    </div>

</body>
</html>